Repository open-thought/reasoning-gym, pull requests merged in 2025-03, with the labels that each got.

#274 fix(envs): Add difficulty in metadata dict where possible
  reasoning_gym/arithmetic/count_bits.py
  reasoning_gym/games/mahjong.py
  reasoning_gym/games/n_queens.py
  reasoning_gym/graphs/course_schedule.py
  reasoning_gym/graphs/largest_island.py
  reasoning_gym/graphs/shortest_path.py
Labels: curriculum

#275 feat(env): Leg Counting Curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/leg_counting.py
  tests/test_leg_counting.py
Labels: curriculum

#278 feat(env): Binary Alternation Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/binary_alternation.py
  tests/test_binary_alternation.py
Labels: curriculum

#276 added basic arith curricula
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/basic_arithmetic.py
  tests/test_basic_arithmetic.py
Labels: curriculum

#279 feat(env): Binary Matrix Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/binary_matrix.py
  tests/test_binary_matrix.py
Labels: curriculum

#280 added Decimal curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/decimal_arithmetic.py
  reasoning_gym/arithmetic/decimal_chain_sum.py
  tests/test_decimal_arithmetic.py
  tests/test_decimal_chain_sum.py
Labels: curriculum

#282 Bitwise arithmetic curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/bitwise_arithmetic.py
  tests/test_bitwise_arithmetic.py
Labels: curriculum

#283 Calendar arithmetic curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/calendar_arithmetic.py
  tests/test_calendar_arithmetic.py
Labels: curriculum

#284 dice curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/dice.py
  tests/test_dice.py
Labels: curriculum

#286 feat(env): Base Conversion Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/base_conversion.py
  tests/test_base_conversion.py
Labels: curriculum

#287 feat(env): Count Primes Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/count_primes.py
  tests/test_count_primes.py
Labels: curriculum

#288 feat(env): Group Anagrams Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/group_anagrams.py
  tests/test_group_anagrams.py
  tests/test_shortest_path.py
Labels: curriculum

#289 Added `word_sorting` curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/word_sorting.py
  tests/test_word_sorting.py
Labels: curriculum

#291 added power function exponent
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/power_function.py
  tests/test_power_function.py
Labels: curriculum

#292 feat(env): Isomorphic Strings Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/isomorphic_strings.py
  tests/test_isomorphic_strings.py
Labels: curriculum

#293 feat(env): Manipulate Matrix Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/manipulate_matrix.py
  tests/test_manipulate_matrix.py
Labels: curriculum

#294 feat(env): Rotate Matrix Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/rotate_matrix.py
  tests/test_rotate_matrix.py
Labels: curriculum

#296 feat(env): Spiral Matrix Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/spiral_matrix.py
  tests/test_spiral_matrix.py
Labels: curriculum

#297 feat(env): Rotten Oranges Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/rotten_oranges.py
  tests/test_rotten_oranges.py
Labels: curriculum

#298 feat(env): Pool Matrix Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/pool_matrix.py
  tests/test_pool_matrix.py
Labels: curriculum

#299 feat(env): Palindrome Partitioning Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/palindrome_partitioning.py
  tests/test_palindrome_partitioning.py
Labels: curriculum

#300 feat(env): Ransom Note Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/ransom_note.py
  tests/test_ransom_note.py
Labels: curriculum

#305 feat(env): String Insertion Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/string_insertion.py
  tests/test_string_insertion.py
Labels: curriculum

#306 feat(env): String Manipulation Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/string_manipulation.py
  tests/test_string_manipulation.py
Labels: curriculum

#309 BF Curricula and More
  reasoning_gym/code/bf.py
  reasoning_gym/cognition/modulo_grid.py
  scripts/generate_gallery.py
  tests/test_bf.py
  tests/test_modulo_grid.py
Labels: curriculum

#313 feat(env): Word Sequence Reversal curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/word_sequence_reversal.py
  tests/test_word_sequence_reversal.py
Labels: curriculum

#312 feat(env): Letter Counting Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/letter_counting.py
  tests/test_letter_counting.py
Labels: curriculum

#307 feat(env): String Splitting Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/string_splitting.py
  tests/test_string_splitting.py
Labels: curriculum

#308 feat(env): String Synthesis Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/string_synthesis.py
  tests/test_string_synthesis.py
Labels: curriculum

#310 Add complex arithmetic curriculum
  reasoning_gym/algebra/complex_arithmetic.py
  tests/test_complex_arithmetic.py
Labels: curriculum

#311 feat(env): Mini Sudoku Curriculum
  reasoning_gym/games/__init__.py
  reasoning_gym/games/mini_sudoku.py
  tests/test_mini_sudoku.py
Labels: curriculum

#314 Curriculum/cognition
  reasoning_gym/cognition/__init__.py
  reasoning_gym/cognition/number_sequences.py
  reasoning_gym/cognition/rectangle_count.py
  tests/test_number_sequences.py
  tests/test_rectangle_count.py
Labels: curriculum

#315 Curriculum/emoji mystery
  reasoning_gym/games/__init__.py
  reasoning_gym/games/emoji_mystery.py
  tests/test_emoji_mystery.py
Labels: curriculum

#316 added futoshiki and tower hanou
  reasoning_gym/games/__init__.py
  reasoning_gym/games/futoshiki.py
  reasoning_gym/games/tower_of_hanoi.py
  tests/test_futoshiki.py
Labels: curriculum

#319 feat(env): Letter Jumble Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/letter_jumble.py
  tests/test_letter_jumble.py
Labels: curriculum

#320 Algebra/curr
  eval/yaml/openai-o1/games.yaml
  reasoning_gym/algebra/__init__.py
  reasoning_gym/algebra/polynomial_equations.py
  reasoning_gym/algebra/simple_integration.py
  tests/test_polynomial_equations.py
  tests/test_simple_integration.py
Labels: curriculum

#321 feat(env): Number Sorting Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/number_sorting.py
  tests/test_number_sorting.py
Labels: curriculum

#322 feat(env): Palindrome Generation Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/palindrome_generation.py
  tests/test_palindrome.py
Labels: curriculum

#323 added Tsumego curriculum
  reasoning_gym/games/__init__.py
  reasoning_gym/games/tsumego.py
  tests/test_tsumego.py
Labels: curriculum

#324 added Quantum Lock curriculum
  reasoning_gym/graphs/__init__.py
  reasoning_gym/graphs/quantum_lock.py
  tests/test_quantum_lock.py
Labels: curriculum

#325 added Sokoban curriculum
  reasoning_gym/games/__init__.py
  reasoning_gym/games/contrib/sokoban/src/generator.py
  reasoning_gym/games/sokoban.py
  tests/test_sokoban.py
Labels: curriculum

#327 feat(env): Spell Backward Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/spell_backward.py
  tests/test_spell_backward.py
Labels: curriculum

#328 Added zebra curriculum
  reasoning_gym/logic/__init__.py
  reasoning_gym/logic/zebra_puzzles.py
  tests/test_zebra.py
Labels: curriculum

#333 feat(env): Number Filtering Curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/number_filtering.py
  tests/test_number_filtering.py
Labels: curriculum

#338 Add polynomial multiplication curriculum
  reasoning_gym/algebra/__init__.py
  reasoning_gym/algebra/polynomial_multiplication.py
  tests/test_polynomial_multiplication.py
Labels: curriculum

#339 Minor fix to advanced geometry
  reasoning_gym/geometry/advanced_geometry.py
Labels: bug

#341 feat(env): Number Formatting Curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/number_format.py
  tests/test_number_format.py
Labels: curriculum

#343 feat(env): Maze Curriculum
  reasoning_gym/games/__init__.py
  reasoning_gym/games/maze.py
  tests/test_maze.py
Labels: curriculum

#344 feat(env): Prime Factorization
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/prime_factorization.py
  tests/test_prime_factorization.py
Labels: curriculum

#345 Add curriculum to ab dataset
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/ab.py
  tests/test_ab.py
Labels: curriculum

#346 Cryptarithm curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/cryptarithm.py
  tests/test_cryptarithm.py
Labels: curriculum

#347 feat(env): Color Cube Rotation Curriculum
  reasoning_gym/cognition/__init__.py
  reasoning_gym/cognition/color_cube_rotation.py
  tests/test_color_cube_rotation.py
Labels: curriculum

#348 feat(env): LCM Curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/lcm.py
  tests/test_lcm.py
Labels: curriculum

#349 feat(env): Fraction Simplification Curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/fraction_simplification.py
  tests/test_fraction_simplification.py
Labels: curriculum

#350 feat(env): Advanced Geometry Curriculum
  reasoning_gym/geometry/__init__.py
  reasoning_gym/geometry/advanced_geometry.py
  tests/test_advanced_geometry.py
Labels: curriculum

#354 Add gol curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/game_of_life.py
  tests/test_game_of_life.py
Labels: curriculum

#355 feat(env): Needle in Haystack Curriculum
  reasoning_gym/cognition/__init__.py
  reasoning_gym/cognition/needle_haystack.py
  tests/test_needle_haystack.py
Labels: curriculum

#356 added aiw curric
  reasoning_gym/logic/__init__.py
  reasoning_gym/logic/aiw.py
  tests/test_aiw.py
Labels: curriculum

#357 feat(env): Rubiks Cube Curriculum
  reasoning_gym/cognition/__init__.py
  reasoning_gym/cognition/rubiks_cube.py
  tests/test_rubiks_cube.py
Labels: curriculum

#358 added Rearc curriculum
  reasoning_gym/arc/__init__.py
  reasoning_gym/arc/rearc.py
  tests/test_rearc.py
Labels: curriculum

#340 Simple equations curriculum
  reasoning_gym/algebra/__init__.py
  reasoning_gym/algebra/simple_equations.py
  tests/test_simple_equations.py
Labels: curriculum

#364 Added Boxnet dataset and curriculum closes #209
  reasoning_gym/games/__init__.py
  reasoning_gym/games/boxnet.py
  tests/test_boxnet.py
Labels: dataset, curriculum

#359 added family relatinship curriculum
  reasoning_gym/graphs/__init__.py
  reasoning_gym/graphs/family_relationships.py
  tests/test_family_relationships.py
Labels: curriculum

#360 add sudoku curriculum
  reasoning_gym/games/__init__.py
  reasoning_gym/games/sudoku.py
  tests/test_sudoku.py
Labels: curriculum

#361 add word ladder curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/word_ladder.py
  tests/test_word_ladder.py
Labels: curriculum

#362 add rush hour curriculum
  reasoning_gym/games/__init__.py
  reasoning_gym/games/rush_hour.py
  tests/test_rush_hour.py
Labels: curriculum

#363 feat(env): Time Intervals Curriculum
  reasoning_gym/arithmetic/__init__.py
  reasoning_gym/arithmetic/time_intervals.py
  tests/test_time_intervals.py
Labels: curriculum

#368 feat(env): Circuit Logic Curriculum
  reasoning_gym/logic/__init__.py
  reasoning_gym/logic/circuit_logic.py
  tests/test_circuit_logic.py
Labels: curriculum

#369 Add jugs curriculum
  reasoning_gym/algorithmic/__init__.py
  reasoning_gym/algorithmic/jugs.py
  tests/test_jugs.py
Labels: curriculum
